basePath: /api/v1
host: localhost:4000
info:
  contact: {}
  description: A Http simple go api
  title: Http-template-api
  version: 0.1.0
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - ping
swagger: "2.0"
