
version: '3'

services:

  reverse-proxy:
    container_name: http-go-template-main-reverse-proxy
    image: nginx:latest
    depends_on:
      - http-go-template
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - dev

  http-go-template:
    container_name: http-go-template-main-prod
    image: http-go-template-main-prod
    build:
      context: ../../../../../
      dockerfile: src/services/main/docker/production/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    entrypoint: ["/app/wait-for.sh", "db:5432", "--", "/app/start.sh"]
    command: ["/app/_main"]
    networks:
      - dev

  db:
    container_name: http-go-template-db-prod
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ps_secret
    ports:
      - "5432:5432"
    networks:
      - dev
networks:
  dev:
    driver: bridge

