name: Project

on:
  push:
    branches:
      - "develop"
env:
  api_port: ${{ vars.API_PORT }}
  db_conn: ${{ secrets.DB_CONN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Get Variables
        run: echo "Api default port ${{ env.api_port }}"

      - name: Get Secrets
        run: echo "Db conn ${{ env.db_conn }}"

      - name: List
        run: echo $(ls -la)
